apiVersion: v2
name: mairror
description: A helm chart to deploy mairror application

type: application

version: 0.0.3

maintainers:
  - name: Alejandro Aceituna
  - name: Borja LÃ³pez

appVersion: "v1.0.0"
